[pytest]
filterwarnings =
    ignore:builtin type .* has no __module__ attribute:DeprecationWarning
    ignore:.*deprecated - use .*:DeprecationWarning:ezdxf\..*
    ignore:.*parseAll.*deprecated.*:DeprecationWarning:pyparsing\.util
